# Generated by Django 4.1.3 on 2022-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
