# Generated by Django 4.1.3 on 2022-11-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_data_site_alter_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
